### ISSUE TITLE
Add: Export to csv or at least print page as pdf to share at the end of the page or per collection

### ISSUE THREAD

**Issue by miguelgargallo** [jessejputnam/card-collector#13]
Add: Export to csv or at least print page as pdf to share at the end of the page or per collection

![image](https://github.com/jessejputnam/card-collector/assets/5947268/d5501926-c253-4288-8844-70b6381cbf14)

**Comment by jessejputnam** [comment]
Added ability to download CSV file of home collection, by set on the set page, and from a filtered selection on the filters page.
