### ISSUE TITLE
Add option to edit, create or delete binders

### ISSUE THREAD

**Issue by 1ntroduc3** [jessejputnam/card-collector#15]
instead of elite and prize binders. I have no idea how complex this is?

**Comment by jessejputnam** [comment]
Hmmmm.... that's a really good idea. I had set it up just for my personal needs and wants, but I love the idea of being able to create specific binders! 

That's going to take some planning out on my end. Also, classic life stuff -- moving to a new state this weekend and work is pushing for extra time put in to finish off a project "on time".

But like I said, I love this idea! I'll try and get to working on it in another week.

**Comment by 1ntroduc3** [comment]
Sounds great @jessejputnam ,

I already tried to do some code modifications with help of chatgpt but can't get it fully working. It would be great to have it. Let me know if I can help with my limited development knowledge!

Good luck with moving this weekend!

**Comment by jessejputnam** [comment]
Alright, the updates are in. You can now create any amount of custom binders now.

**Comment by 1ntroduc3** [comment]
Amazing! I will check it out. Thanks a lot
