### ISSUE TITLE
MongoDB Card Document 

### ISSUE THREAD

**Issue by patriksramoss** [jessejputnam/card-collector#2]
Can you add a MongoDB document including metadata to add all the pokemon cards to our MongoDB database?

**Comment by jessejputnam** [comment]
Hi, I am not sure I quite understand what you are asking. I added the .env hints to the readme though. If you are looking for the data for all the cards, check the readme for the link to the PokeAPI -- it's the database I used for the card information.

**Comment by patriksramoss** [comment]
Thanks! Also I didn't realize that you were using an API for the Cards database, sorry about that.
